# Generated by Django 5.1 on 2025-01-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePost',
        ),
    ]
